### ISSUE TITLE
Add needed depandancies for theme

### ISSUE THREAD

**Issue by sentakuhm** [rototrash/tokyo-night-sddm#3]
There are two needed tools for the theme you can mention em on description:
`qt5-quickcontrols2` and `qt5-graphicaleffects`

**Comment by Jj1910** [comment]
There's a further dependency to unpack the image files, ````qt5-svg```` without this you'll get errors that the images for the power buttons are in an unsupported svgz format and they won't display.

**Comment by siddrs** [comment]
Updated the readme. Thanks for reporting.
